[annotation_1]
strokeWidth = 2
shape = "mxgraph.flowchart.annotation_1"
align = "left"
pointerEvents = 1
size = [50, 100]

[annotation_2]
strokeWidth = 2
shape = "mxgraph.flowchart.annotation_2"
align = "left"
labelPosition = "right"
pointerEvents = 1
size = [50, 100]

[card]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "card"
whiteSpace = "wrap"
# size = 20
arcSize = 12
size = [100, 60]

[collate]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "mxgraph.flowchart.collate"
size = [100, 100]

[data]
shape = "parallelogram"
strokeWidth = 2
perimter = "parallelogramPerimeter"
whiteSpace = "wrap"
rounded = 1
arcSize = 12
# size = 0.23
size = [100, 60]

[database]
strokeWidth = 2
shape = "mxgraph.flowchart.database"
whiteSpace = "wrap"

[decision]
strokeWidth = 2
shape = "mxgraph.flowchart.decision"
whiteSpace = "wrap"

[delay]
strokeWidth = 2
shape = "mxgraph.flowchart.delay"
whiteSpace = "wrap"

[direct_data]
strokeWidth = 2
shape = "mxgraph.flowchart.direct_data"
whiteSpace = "wrap"

[display]
strokeWidth = 2
shape = "mxgraph.flowchart.display"
whiteSpace = "wrap"
size = 0.25

[document]
strokeWidth = 2
shape = "mxgraph.flowchart.display2"
whiteSpace = "wrap"
size = 0.25

[extract]
strokeWidth = 2
shape = "mxgraph.flowchart.extract_or_measurement"
whiteSpace = "wrap"

[measurement]
strokeWidth = 2
shape = "mxgraph.flowchart.extract_or_measurement"
whiteSpace = "wrap"

[internal_storage]
shape = "internalStorage"
whiteSpace = "wrap"
dx = 15
dy = 15
rounded = 1
arcSize = 8
StrokeWidth = 2

[loop_limit]
strokeWidth = 2
shape = "mxgraph.flowchart.loop_limit"
whiteSpace = "wrap"

[manual_input]
strokeWidth = 2
shape = "manualInput"
whiteSpace = "wrap"
rounded = 1
size = 26
arcSize = 11

[manual_operation]
verticalLabelPosition = "middle"
verticalAlign = "middle"
shape = "trapezoid"
perimeter = "trapezoidperimeter"
whiteSpace = "wrap"
size = 0.23
arcSize = 10
flipV = 1
labelPosition = "center"
align = "center"

[merge]
strokeWidth = 2
shape = "mxgraph.flowchart.merge_or_storage"
whiteSpace = "wrap"

[storage]
strokeWidth = 2
shape = "mxgraph.flowchart.merge_or_storage"
whiteSpace = "wrap"

[multi_document]
strokeWidth = 2
shape = "mxgraph.flowchart.multi-document"
whiteSpace = "wrap"

[off_page_ref]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "offPageConnector"
rounded = 0
size = 0.5

[on_page_ref]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "mxgraph.flowchart.on-page_reference"

[or]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "mxgraph.flowchart.summing_function"

[tape]
shape = "tape"
whiteSpace = "wrap"
strokeWidth = 2
size = 0.19

[parallel_mode]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "mxgraph.flowchart.parallel_mode"
pointerEvents = 1

[predefined_process]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "process"
whiteSpace = "wrap"
rounded = 1
size = 0.14
arcSize = 6

[preparation]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "hexagon"
perimeter = "hexagonPerimeter2"
arcSize = 6
size = 0.27

[process]
rounded = 1
whiteSpace = "wrap"
absoluteArcSize = 1
arcSize = 14
strokeWidth = 2

[sequential_data]
strokeWidth = 2
shape = "mxgraph.flowchart.sequential_data"
whiteSpace = "wrap"

[sort]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "mxgraph.flowchart.sort"

[start_1]
strokeWidth = 2
shape = "mxgraph.flowchart.start_1"
whiteSpace = "wrap"

[start_2]
strokeWidth = 2
shape = "mxgraph.flowchart.start_2"
whiteSpace = "wrap"

[stored_data]
strokeWidth = 2
shape = "mxgraph.flowchart.stored_data"
whiteSpace = "wrap"

[summing_junction]
verticalLabelPosition = "bottom"
verticalAlign = "top"
shape = "mxgraph.flowchart.or"

[terminator]
strokeWidth = 2
shape = "mxgraph.flowchart.terminator"
whiteSpace = "wrap"

[transfer]
verticalLabelPosition = "bottom"
verticalAlign = "top"
strokeWidth = 2
shape = "mxgraph.arrows2.arrow"
dy = 0.6
dx = 40
notch = 0